<a href="https://colab.research.google.com/github/maazali04/Python-Data-Science-Foundations/blob/main/Numpy_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Making an array

In [ ]:
# How to make an np array
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
# datatype
type(np.array([1,2,3]))

numpy.ndarray

In [ ]:
# make 0d, 1D, 2D, 3D array
scalar = np.array(25) # 0D
vector = np.array([1,2,3,4,5]) # 1D
matrix = np.array([[1,2,3],[4,5,6]]) # 2D

# .ndim represents number of dimensions
# .shape represents number of elements in each dimension

print(scalar, scalar.ndim, scalar.shape)
print("-" * 5)
print(vector, vector.ndim, vector.shape)
print("-" * 5)
print(matrix, matrix.ndim, matrix.shape)



25 0 ()
-----
[1 2 3 4 5] 1 (5,)
-----
[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [ ]:
# make ndarray with specific number of dimension
custom_ndarray = np.array([1,2,3,4], ndmin=3)
print(custom_ndarray)
print("-"* 5)
print(custom_ndarray.ndim)
print("-"* 5)
print(custom_ndarray.shape)

[[[1 2 3 4]]]
-----
3
-----
(1, 1, 4)


# Access Array Elements


In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr1[0], arr1[1]

(np.int64(1), np.int64(2))

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2[0,2], arr2[1,2]

(np.int64(3), np.int64(6))

(np.int64(3), np.int64(6))

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3[0,0,2], arr3[1,1,2]

(np.int64(3), np.int64(12))

## Slicing

In [ ]:
#  1D
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[-3:-1])
print(arr[1:5:2])

[2 3 4 5]
[5 6]
[2 4]


In [ ]:
# 2D
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])

[7 8 9]
[3 8]


In [ ]:
# 3D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 0:2])
print(arr[1, 0:2, 2])

[4 5]
[ 9 12]


# Datatype

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype # Unicode String

dtype('<U6')

In [ ]:
arr = np.array([1., 2, 3, 4])
arr.dtype

dtype('float64')

In [ ]:
arr = np.array([True,True])
arr.dtype

dtype('bool')

In [ ]:
#  The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
newarr

array([1, 2, 3], dtype=int32)

# Different Methods (Functions)

In [ ]:
# Copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
arr, x

(array([42,  2,  3,  4,  5]), array([1, 2, 3, 4, 5]))

In [ ]:
# View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
arr, x

(array([42,  2,  3,  4,  5]), array([42,  2,  3,  4,  5]))

In [ ]:
# base return none if array owns the data othewise return the original object
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Reshaping array

In [ ]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#  Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#  Unknown Dimension
#  put -1 for the unknonw dimension
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Flattening the arrays
# convert ndim to 1D
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## Iterating

In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
# nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr): # nditer prevents us from nested loops
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
# ndenumerate
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
# concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
#  joining along row
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Stack - one over the other
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# stack along columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# dstack - add new dimension
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Split an array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## Search

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


## Sort

In [ ]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filter

In [ ]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


## Matrix Multiplication


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"Element-wise multiplication: \n{A * B}")
print(f"Matrix multiplication: \n{A @ B}")

Element-wise multiplication: 
[[ 5 12]
 [21 32]]
Matrix multiplication: 
[[19 22]
 [43 50]]


## Broadcasting

In [5]:
arr = np.array([1,2,3])
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)
print(arr ** 10)

[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.1 0.2 0.3]
[    1  1024 59049]


## Statistical Operations

In [6]:
data = np.array([10, 20, 30, 40, 50])

In [7]:
# Mean
np.mean(data)

np.float64(30.0)

In [9]:
# Median
np.median(data)

np.float64(30.0)

In [10]:
# Min
np.min(data)

np.int64(10)

In [11]:
# Max
np.max(data)

np.int64(50)

In [12]:
# sum
np.sum(data)

np.int64(150)

In [13]:
# variance
np.var(data)

np.float64(200.0)

In [14]:
# standard deviation
np.std(data)

np.float64(14.142135623730951)

## Random Module

In [25]:
np.random.randint(100) # between 0 and 100 (exclusive)

0

In [23]:
np.random.rand() # between 0 and 1

0.5056898716634495

In [34]:
np.random.randn() # normal distribution

-1.129107409794226

## Vectorization

- It treat the entire array as a single mathematical vector.
- It is faster than loops

In [36]:
numbers_arr = np.array([1, 2, 3, 4, 5])
result = numbers_arr * 2
result

array([ 2,  4,  6,  8, 10])